'use client'

import { useEffect, useState } from 'react'
import { Check, Inbox, Save } from 'lucide-react'

type RequestItem = { id:string; name:string; phone:string; country:string; nationalId:string|null; age:number|null; guardianName:string|null; juz:string|null; surah:string|null; notes:string|null; status:string }

export function AdminRequests() {
  const [items, setItems] = useState<RequestItem[]>([])
  const [phone, setPhone] = useState('201554542019')
  const [saved, setSaved] = useState(false)
  async function load() { const [requests, settings] = await Promise.all([fetch('/api/admin/requests').then(r=>r.json()), fetch('/api/admin/settings').then(r=>r.json())]); setItems(requests.requests || []); setPhone(settings.whatsappNumber) }
  useEffect(() => { void load() }, [])
  async function approve(id:string) { await fetch('/api/admin/requests', { method:'PATCH', headers:{'content-type':'application/json'}, body:JSON.stringify({id,status:'approved'}) }); await load() }
  async function savePhone() { await fetch('/api/admin/settings', { method:'PUT', headers:{'content-type':'application/json'}, body:JSON.stringify({whatsappNumber:phone}) }); setSaved(true); window.setTimeout(()=>setSaved(false),2000) }
  return <section dir="rtl" className="border-b border-border bg-background px-5 py-8 text-foreground"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="flex items-center gap-2 text-sm text-primary"><Inbox size={17}/> بطاقة الرسائل</p><h1 className="mt-2 text-3xl font-bold">طلبات الانضمام</h1><p className="mt-2 text-muted-foreground">راجع البيانات، ثم أضف الطالب يدويًا من خانة إضافة طالب جديد واضغط موافقة.</p></div><div className="rounded-2xl border border-border bg-card p-4"><label className="text-sm font-medium">رقم واتساب المسؤول</label><div className="mt-2 flex gap-2"><input dir="ltr" value={phone} onChange={(e)=>setPhone(e.target.value)} className="rounded-lg border border-input bg-background px-3 py-2"/><button onClick={savePhone} className="flex items-center gap-2 rounded-lg bg-primary px-3 py-2 text-primary-foreground"><Save size={16}/>{saved?'تم':'حفظ'}</button></div></div></div><div className="mt-6 grid gap-4 lg:grid-cols-2">{items.length ? items.map((item)=><article key={item.id} className="rounded-2xl border border-border bg-card p-5"><div className="flex items-start justify-between gap-4"><div><h2 className="text-xl font-bold">{item.name}</h2><p dir="ltr" className="mt-1 text-right text-sm text-muted-foreground">{item.phone}</p></div><span className="rounded-full bg-secondary px-3 py-1 text-xs">{item.status==='approved'?'تمت الموافقة':'قيد التنفيذ'}</span></div><dl className="mt-5 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-muted-foreground">البلد</dt><dd>{item.country}</dd></div><div><dt className="text-muted-foreground">الرقم القومي</dt><dd>{item.nationalId||'-'}</dd></div><div><dt className="text-muted-foreground">السن</dt><dd>{item.age||'-'}</dd></div><div><dt className="text-muted-foreground">ولي الأمر</dt><dd>{item.guardianName||'-'}</dd></div><div><dt className="text-muted-foreground">الجزء</dt><dd>{item.juz||'-'}</dd></div><div><dt className="text-muted-foreground">السورة</dt><dd>{item.surah||'-'}</dd></div></dl>{item.notes&&<p className="mt-4 rounded-lg bg-secondary p-3 text-sm">{item.notes}</p>}{item.status!=='approved'&&<button onClick={()=>approve(item.id)} className="mt-5 flex items-center gap-2 rounded-lg bg-primary px-4 py-2 text-primary-foreground"><Check size={16}/> تمت إضافة الطالب — موافقة</button>}</article>):<div className="rounded-2xl border border-dashed border-border p-8 text-center text-muted-foreground">لا توجد طلبات انضمام حتى الآن</div>}</div></div></section>
}
