'use client'

import { useEffect, useMemo, useState } from 'react'
import { Eye, Fingerprint, ShieldCheck, SlidersHorizontal, TimerReset } from 'lucide-react'

export type AntiCheatConfig = {
  enabled: boolean; requireCamera: boolean; eyeTracking: boolean; gaze: boolean; singleTouch: boolean; warnOnAway: boolean; facePresence: boolean; multipleFaces: boolean; headPose: boolean; eyeClosure: boolean; focus: boolean; fullscreen: boolean; warningThreshold: number; suspiciousThreshold: number; cheatingThreshold: number; graceMs: number; blockMs: number; autoRestore: boolean; analysisIntervalMs: number; sensitivity: 'low' | 'medium' | 'high'
}

export const defaultAntiCheatConfig: AntiCheatConfig = { enabled: false, requireCamera: true, eyeTracking: true, gaze: true, singleTouch: true, warnOnAway: true, facePresence: true, multipleFaces: true, headPose: true, eyeClosure: true, focus: true, fullscreen: false, warningThreshold: 20, suspiciousThreshold: 45, cheatingThreshold: 75, graceMs: 2500, blockMs: 8000, autoRestore: true, analysisIntervalMs: 400, sensitivity: 'medium' }
type Item = { itemId: string; itemType: 'recitation' | 'exam' | 'task'; label: string }
const defaultItems: Item[] = [{ itemId: 'demo-quiz', itemType: 'recitation', label: 'التسميع الحالي' }, { itemId: 'demo-quiz', itemType: 'exam', label: 'الاختبار الحالي' }, { itemId: 'demo-quiz', itemType: 'task', label: 'المهمة الحالية' }]

export function AntiCheatSettings({ value, onChange, items = defaultItems }: { value: AntiCheatConfig; onChange: (value: AntiCheatConfig) => void; items?: Item[] }) {
  const [global, setGlobal] = useState(false); const [overrides, setOverrides] = useState<Record<string, boolean>>({}); const [status, setStatus] = useState(''); const [loading, setLoading] = useState(true)
  const key = (item: Item) => `${item.itemId}:${item.itemType}`
  const load = async () => { setLoading(true); try { const response = await fetch('/api/anti-cheat'); if (!response.ok) throw new Error(); const data = await response.json(); setGlobal(Boolean(data.global?.enabled)); setOverrides(Object.fromEntries((data.items ?? []).map((item: { itemId: string; itemType: string; enabled: boolean }) => [`${item.itemId}:${item.itemType}`, item.enabled]))) } catch { setStatus('تعذر تحميل الإعدادات من الخادم') } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  const update = (patch: Partial<AntiCheatConfig>) => onChange({ ...value, ...patch })
  const saveGlobal = async (enabled: boolean) => { setStatus('Saving...'); try { const response = await fetch('/api/anti-cheat', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ action: 'save-global', enabled }) }); if (!response.ok) throw new Error(); const data = await response.json(); setGlobal(Boolean(data.global.enabled)); setStatus('Saved') } catch { setStatus('Error') } }
  const saveItem = async (item: Item, enabled: boolean) => { setStatus('Saving...'); try { const response = await fetch('/api/anti-cheat', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ action: 'save-config', item: { itemId: item.itemId, itemType: item.itemType, enabled, config: value } }) }); if (!response.ok) throw new Error(); const data = await response.json(); setOverrides((current) => ({ ...current, [key(item)]: Boolean(data.item.enabled) })); setStatus('Saved') } catch { setStatus('Error') } }
  const rows = useMemo(() => [{ key: 'eyeTracking', icon: Eye, title: 'متابعة اتجاه النظر', description: 'تحليل محلي منخفض المعدل.' }, { key: 'singleTouch', icon: Fingerprint, title: 'لمسة إصبع واحدة', description: 'في أي مكان على الشاشة.' }, { key: 'warnOnAway', icon: TimerReset, title: 'تنبيه عند الابتعاد', description: 'يقيس المدة والتكرار.' }] as const, [])
  return <section aria-labelledby="anti-cheat-title" className="rounded-2xl border border-border bg-card p-5 shadow-sm"><div className="flex items-start justify-between gap-4"><div className="flex gap-3"><div className="rounded-xl bg-primary/10 p-2.5 text-primary"><ShieldCheck /></div><div><p className="font-mono text-[11px] uppercase tracking-[0.18em] text-primary">تسميع / اختبار / مهمة</p><h2 id="anti-cheat-title" className="mt-1 text-xl font-bold">إعدادات مكافحة الغش</h2><p className="mt-1 max-w-xl text-sm leading-6 text-muted-foreground">Global Default يُستخدم عند الإنشاء فقط؛ كل override محفوظ مستقل.</p></div></div><button type="button" aria-pressed={global} disabled={loading} onClick={() => { setGlobal(!global); void saveGlobal(!global) }} className={`relative h-7 w-12 shrink-0 rounded-full transition ${global ? 'bg-primary' : 'bg-muted'}`}><span className={`absolute top-1 size-5 rounded-full bg-background transition ${global ? 'right-1' : 'right-6'}`} /></button></div><div className="mt-5 space-y-2"><p className="text-sm font-semibold">العناصر المعزولة حسب itemId + itemType</p>{items.map((item) => <div key={key(item)} className="flex items-center justify-between rounded-xl border border-border/80 p-3"><span className="text-sm">{item.label} <span className="text-xs text-muted-foreground">({item.itemId} · {item.itemType})</span></span><button type="button" aria-pressed={overrides[key(item)] ?? global} onClick={() => void saveItem(item, !(overrides[key(item)] ?? global))} className={`relative h-6 w-11 rounded-full ${overrides[key(item)] ?? global ? 'bg-primary' : 'bg-muted'}`}><span className={`absolute top-1 size-4 rounded-full bg-background transition ${overrides[key(item)] ?? global ? 'right-1' : 'right-6'}`} /></button></div>)}</div><div className="mt-5 flex flex-col gap-3 opacity-100"><p className="text-xs font-semibold text-muted-foreground">تفاصيل الإعداد العام</p>{rows.map(({ key: field, icon: Icon, title, description }) => <label key={field} className="flex cursor-pointer items-center justify-between gap-4 rounded-xl border border-border/80 p-3.5"><span className="flex items-center gap-3"><Icon className="text-primary" /><span><span className="block text-sm font-semibold">{title}</span><span className="block text-xs text-muted-foreground">{description}</span></span></span><input type="checkbox" checked={Boolean(value[field])} onChange={(event) => update({ [field]: event.target.checked })} className="size-4 accent-primary" /></label>)}</div><div className="mt-4 flex items-center justify-between gap-3"><p className="text-xs text-muted-foreground">مصدر القرار الأمني: الخادم وقاعدة البيانات.</p><span role="status" className="text-xs font-semibold text-primary">{status}</span></div></section>
}

export function AntiCheatSummary({ config }: { config: AntiCheatConfig }) { return <div className="rounded-xl border border-border bg-secondary/50 p-4"><div className="flex items-center gap-2 text-sm font-semibold"><SlidersHorizontal className="text-primary" /> الحماية {config.enabled ? 'مفعّلة' : 'غير مفعّلة'}</div><p className="mt-2 text-xs leading-5 text-muted-foreground">تُطبّق إعدادات العنصر المحفوظة من الخادم.</p></div> }
