'use client'

import { useEffect, useRef, useState } from 'react'
import { Camera, CheckCircle2, Eye, Fingerprint, TriangleAlert } from 'lucide-react'
import type { AntiCheatConfig } from './anti-cheat-settings'

export function StudentProctor({ config }: { config: AntiCheatConfig }) {
  const videoRef = useRef<HTMLVideoElement>(null)
  const [camera, setCamera] = useState<'idle' | 'ready' | 'blocked'>('idle')
  const [touches, setTouches] = useState(0)
  const [warning, setWarning] = useState('')
  useEffect(() => { if (!config.enabled || !config.eyeTracking) return; let stream: MediaStream | undefined; navigator.mediaDevices?.getUserMedia({ video: { facingMode: 'user' }, audio: false }).then((value) => { stream = value; if (videoRef.current) videoRef.current.srcObject = value; setCamera('ready') }).catch(() => setCamera('blocked')); return () => stream?.getTracks().forEach((track) => track.stop()) }, [config.enabled, config.eyeTracking])
  useEffect(() => { if (!config.enabled || !config.singleTouch) return; const onStart = (event: TouchEvent) => { setTouches(event.touches.length); if (event.touches.length !== 1) setWarning('يُرجى استخدام إصبع واحد فقط أثناء التسميع.') }; const onEnd = (event: TouchEvent) => { setTouches(event.touches.length); if (!event.touches.length) setWarning('تم فقدان اللمس. المس الشاشة مرة أخرى للمتابعة.') }; window.addEventListener('touchstart', onStart, { passive: true }); window.addEventListener('touchend', onEnd, { passive: true }); return () => { window.removeEventListener('touchstart', onStart); window.removeEventListener('touchend', onEnd) } }, [config.enabled, config.singleTouch])
  if (!config.enabled) return null
  return <section aria-labelledby="student-monitor-title" className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center justify-between gap-3"><div><p className="font-mono text-[11px] tracking-[0.18em] text-primary">وضع الطالب</p><h2 id="student-monitor-title" className="mt-1 text-lg font-bold">مراقبة التسميع</h2></div><span className="flex items-center gap-1.5 rounded-full bg-primary/10 px-3 py-1 text-xs text-primary"><CheckCircle2 /> فحص محلي</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="relative overflow-hidden rounded-xl bg-secondary"><video ref={videoRef} autoPlay muted playsInline className="aspect-video w-full object-cover opacity-80" /><div className="absolute inset-0 flex items-center justify-center">{camera === 'ready' ? <Eye className="text-primary" /> : camera === 'blocked' ? <span className="flex items-center gap-2 text-xs text-muted-foreground"><Camera /> الكاميرا غير متاحة</span> : <span className="text-xs text-muted-foreground">سيطلب المتصفح إذن الكاميرا</span>}</div></div><div className="flex flex-col gap-3"><div className="flex items-center gap-3 rounded-xl border border-border p-3"><Eye className="text-primary" /><div><p className="text-sm font-semibold">اتجاه العين</p><p className="text-xs text-muted-foreground">تنبيه عند الابتعاد عن الشاشة</p></div></div><div className="flex items-center gap-3 rounded-xl border border-border p-3"><Fingerprint className="text-primary" /><div><p className="text-sm font-semibold">اللمس: {touches === 1 ? 'إصبع واحد' : 'جاهز'}</p><p className="text-xs text-muted-foreground">الموقع يعمل طبيعيًا في أي مكان</p></div></div></div></div>{warning && <div role="alert" className="mt-4 flex items-center gap-2 rounded-xl border border-destructive/40 bg-destructive/10 p-3 text-sm text-destructive"><TriangleAlert /> {warning}</div>}</section>
}
