'use client'

import { useEffect, useRef, useState } from 'react'
import { Camera, CheckCircle2, Eye, Fingerprint, ShieldAlert, TriangleAlert } from 'lucide-react'
import type { AntiCheatConfig } from './anti-cheat-settings'
import { calculateRiskScore, severityFor, shouldRecord, type AntiCheatSeverity } from '@/lib/anti-cheat-engine'

type Props = { config: AntiCheatConfig; studentId?: string; itemId?: string; itemType?: string }
const copy: Record<AntiCheatSeverity, string> = { NORMAL: 'المراقبة طبيعية', WARNING: 'تنبيه: راجع وضع الاختبار', SUSPICIOUS: 'اشتباه: عدة إشارات مستمرة', CHEATING_DETECTED: 'تم إيقاف التحكم مؤقتًا' }

export function StudentProctor({ config, studentId = 'student', itemId = 'item', itemType = 'exam' }: Props) {
  const videoRef = useRef<HTMLVideoElement>(null); const started = useRef(false); const sessionId = useRef(''); const stream = useRef<MediaStream | undefined>(undefined); const landmarker = useRef<import('@mediapipe/tasks-vision').FaceLandmarker | undefined>(undefined); const durations = useRef(new Map<string, number>()); const score = useRef(0); const lastEvent = useRef(new Map<string, number>())
  const [state, setState] = useState('loading'); const [severity, setSeverity] = useState<AntiCheatSeverity>('NORMAL'); const [riskScore, setRiskScore] = useState(0); const [warning, setWarning] = useState(''); const [blocked, setBlocked] = useState(false); const [touches, setTouches] = useState(0)
  useEffect(() => { if (!config.enabled) return; let alive = true; let raf = 0; let last = 0
    const post = async (body: unknown) => { try { await fetch('/api/anti-cheat', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body), keepalive: true }) } catch {} }
    const record = (type: string, active: boolean, now: number, weight: number) => { const begun = durations.current.get(type) ?? now; if (active) durations.current.set(type, begun); else durations.current.delete(type); const duration = active ? now - begun : 0; const signals = [...durations.current].map(([key, value]) => ({ type: key, active: true, durationMs: now - value, weight: key === 'multiple-faces' ? 35 : weight })); score.current = calculateRiskScore(signals, score.current); const next = severityFor(score.current, config); setRiskScore(score.current); setSeverity(next); if (next === 'CHEATING_DETECTED') setBlocked(true); if (active && shouldRecord({ type, active, durationMs: duration, weight }, config) && now - (lastEvent.current.get(type) ?? 0) > 3000) { lastEvent.current.set(type, now); setWarning(copy[next]); void post({ action: 'event', event: { sessionId: sessionId.current, studentId, itemId, eventType: type, riskScore: score.current, severity: next, durationMs: duration } }) } }
    const onVisibility = () => record(document.hidden ? 'page-hidden' : 'page-visible', document.hidden, performance.now(), 15); const onBlur = () => record('window-blur', true, performance.now(), 12); const onFocus = () => record('window-blur', false, performance.now(), 12); const onTouch = (e: TouchEvent) => { setTouches(e.touches.length); record('multiple-touch', e.touches.length > 1, performance.now(), 25) }
    document.addEventListener('visibilitychange', onVisibility); window.addEventListener('blur', onBlur); window.addEventListener('focus', onFocus); window.addEventListener('touchstart', onTouch, { passive: true }); window.addEventListener('touchmove', onTouch, { passive: true });
    const start = async () => { try { setState('loading'); const r = await fetch('/api/anti-cheat', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ action: 'start', session: { studentId, itemId, itemType, config } }) }); const data = await r.json(); if (!r.ok) throw new Error(); if (data.disabled || !data.config?.enabled) { setState('disabled'); return } sessionId.current = data.sessionId; if (!navigator.mediaDevices?.getUserMedia) throw new Error('camera-unsupported'); stream.current = await navigator.mediaDevices.getUserMedia({ video: true, audio: false }); if (!videoRef.current) return; videoRef.current.srcObject = stream.current; await videoRef.current.play(); started.current = true; setState('ready'); const vision = await import('@mediapipe/tasks-vision'); const fileset = await vision.FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22/wasm'); landmarker.current = await vision.FaceLandmarker.createFromOptions(fileset, { baseOptions: { modelAssetPath: 'https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/1/face_landmarker.task', delegate: 'GPU' }, runningMode: 'VIDEO', numFaces: 2, minFaceDetectionConfidence: .6 }); const detect = () => { if (!alive || !videoRef.current || !landmarker.current) return; const now = performance.now(); if (now-last >= config.analysisIntervalMs && videoRef.current.readyState >= 2) { last=now; const result=landmarker.current.detectForVideo(videoRef.current, now); const count=result.faceLandmarks.length; record('face-missing', count===0, now, 20); record('multiple-faces', count>1, now, 35); if(count===1){ const face=result.faceLandmarks[0]; const nose=face[1], left=face[234], right=face[454]; const turned=Math.abs((nose.x-left.x)/Math.max(right.x-left.x,.001)-.5)>.2; record('head-turn', turned, now, 18); const iris=face[468], outer=face[33], inner=face[133]; const gaze=Math.abs((iris.x-outer.x)/Math.max(inner.x-outer.x,.001)-.5)>.18; record('gaze-away', gaze, now, 16); } else { record('head-turn', false, now, 18); record('gaze-away', false, now, 16) } } raf=requestAnimationFrame(detect) }; detect() } catch { setState('blocked'); if(config.requireCamera) setWarning('يجب السماح باستخدام الكاميرا لإجراء هذا الاختبار لأن فحص الغش مفعل.') } }
    void start(); return () => { alive=false; cancelAnimationFrame(raf); document.removeEventListener('visibilitychange', onVisibility); window.removeEventListener('blur', onBlur); window.removeEventListener('focus', onFocus); window.removeEventListener('touchstart', onTouch); window.removeEventListener('touchmove', onTouch); stream.current?.getTracks().forEach((t)=>t.stop()); landmarker.current?.close(); if(sessionId.current) void post({ action:'end', session:{ id:sessionId.current, riskScore:score.current, severity:severityFor(score.current,config) } }) }
  }, [config, studentId, itemId, itemType])
  if (!config.enabled) return null
  return <section aria-label="نظام المراقبة" className="relative rounded-2xl border border-border bg-card p-4"><div className="flex items-center justify-between"><div><p className="text-xs text-primary">جلسة مراقبة واحدة</p><h2 className="font-bold">فحص متعدد الإشارات</h2></div><span className="text-xs text-muted-foreground">{state === 'ready' ? 'جاهز' : 'تهيئة'}</span></div><div className="mt-4 grid gap-4 sm:grid-cols-2"><video ref={videoRef} autoPlay muted playsInline className="aspect-video w-full rounded-xl bg-secondary object-cover" aria-label="كاميرا الطالب" /><div className="space-y-3"><div className="rounded-xl border border-border p-3"><div className="flex items-center gap-2"><Eye className="text-primary" />{copy[severity]}</div><p className="mt-2 text-sm">Risk Score: {riskScore}/100</p></div><div className="flex items-center gap-2 rounded-xl border border-border p-3 text-sm"><Fingerprint className="text-primary" /> اللمس الحالي: {touches}</div><div className="flex items-center gap-2 text-xs text-muted-foreground"><CheckCircle2 className="text-primary" /> تحليل محلي دون رفع فيديو</div></div></div>{warning && <div role="alert" className="mt-4 flex gap-2 rounded-xl bg-destructive/10 p-3 text-sm text-destructive"><TriangleAlert />{warning}</div>}{blocked && <div className="absolute inset-0 z-10 flex items-center justify-center rounded-2xl bg-background/95 p-6 text-center"><div><ShieldAlert className="mx-auto mb-3 text-destructive" /><p className="font-bold">تم منع التحكم مؤقتًا</p><p className="mt-2 text-sm text-muted-foreground">سيتم استرجاع الشاشة وفق سياسة المهمة بعد انتهاء الإشارة.</p></div></div>}</section>
}
